chore: remove nanoid and react-native-redash to clean up some build issues
gorhom/react-native-bottom-sheet pull request #1046
Opened 2022-08-01 17:26 UTC by natew

redash especially causes build issues, bit cleaned up nanoid while I was there.

2022-08-01 17:43 UTC, natew commented
Fixes https://github.com/gorhom/react-native-bottom-sheet/issues/1020

2022-08-15 15:41 UTC, gorhom requested changes
Thanks @natew for submitting this PR, all looks fine except the removal of `invariant` package, it is still needed for now

2022-08-15 15:41 UTC, gorhom commented on package.json
> -    "invariant": "^2.2.4",
`invariant` is needed, till it get replaced with `proptypes`

2022-08-30 18:44 UTC, hirbod commented
Anything I can do to get this merged? :)

2022-09-09 18:26 UTC, gorhom approved these changes

2022-09-09 18:26 UTC, gorhom commented
thanks @natew for submitting this PR !

2022-09-09 18:26 UTC, merged