fix(bottom-sheet-modal): behind native modal view
gorhom/react-native-bottom-sheet pull request #1309
Opened 2023-03-02 09:47 UTC by magrinj

Fix issue #832 

## Motivation

Using `react-navigation` or native `Modal` component with `BottomSheetModal` component will show them behind the native views.

As suggested in react-native-portal library, we should wrap the content inside `FullWindowOverlay` to get the view above all the native views.

https://github.com/gorhom/react-native-portal#react-native-screens-integration

I had initially create this PR #1086 to fix the issue, but this one fix the concern about adding `react-native-screens` as a required dependency.

`react-native-screens` is now added but as an optional peer dependency.
If the module is installed the `FullWindowOverlay` will be used on iOS, otherwise it will work as before.

2023-03-15 12:26 UTC, joseortiz9 commented
@gorhom hope you can check this PR, nice work
UP +1

2023-03-17 13:11 UTC, batuhansahan commented
this does not work with react navigation ios modals(presentation: 'modal'). bottom-sheet bottom insets jumping up.

2023-03-17 13:40 UTC, magrinj commented
@batuhansahan Not sure to understand what is actually not working on your side, can you provide a sample ?

2023-03-17 13:50 UTC, batuhansahan commented
bottom sheet looks like this. I properly set up `<BottomSheetModalProvider>` And `BottomSheetModal`. bottominset is already 0, 
the goal of using your pr because hoping to fix that where swiping down to dismiss a bottom sheet was also closing the underlying ios-modal behind it, PR is fixing the swipe conflict WELL DONE!. but bottom sheet is not in correct position.
![simulator_screenshot_4FDA2970-284F-4086-A8C9-28EBAF684CE8](https://user-images.githubusercontent.com/26772801/225924734-17c88631-180c-4595-9875-5cdf9370c26e.jpg)

2023-03-17 15:33 UTC, magrinj commented
Hmm strange, maybe your `BottomSheetModalProvider` is not correctly placed.
On my side I'm using this library https://github.com/th3rdwave/react-navigation-bottom-sheet
It allows to use bottom sheet with the same api as react-navigation and it's working really well on my side with presentation modal using native stack from react-navigation.

2023-03-18 19:16 UTC, batuhansahan commented
i tried everything 

provider
navigationcontainer
or reverse. 

that package seems to using stack navigator not native stack

2023-03-18 19:19 UTC, batuhansahan commented
i tried very way

-provider
--navigation container

or reverse.

2023-04-14 09:15 UTC, thecoorum commented
It's also not working for me with the following screen options
```
animation: 'none',
presentation: 'transparentModal'
```
It's always rendered behind the stack screen

2023-05-14 21:23 UTC, magrinj commented
@gorhom Any news on this ?

2023-05-16 07:50 UTC, thecoorum commented
It is working for me with the `BottomSheetModalProvider` around `NavigationContainer` when my screens have the following options
```
animation: 'none',
presentation: 'transparentModal'
```

The only thing is that screens are implemented with regular `BottomSheet`, but some nested modals with `BottomSheetModal`. I think if implementing both with modals there is some portaling issue

2023-05-29 21:34 UTC, erickreutz commented
Would love to see this merged!

2023-05-31 19:22 UTC, thecoorum commented
I noticed that this implementation conflicts with libraries like `react-native-ios-context-menu`. If you are rendering dropdown menu in such modal it will be just invisible

2023-06-02 07:15 UTC, magrinj commented
@thecoorum Actually it’s not invisible but behind the bottom sheet because of the `FullWindowOverlay`, maybe I can add a boolean prop to enable/disable the use of the `FullWindowOverlay` with a default value of `true`.
But when disabled the problem of the bottom sheet behind modals will appear again.
It really depends on how your screens are implemented and looks like, the main goal of this fix is to solve the issue when using `@react-navigation/native-stack` modals, bottom sheet appear behind them.

2023-06-04 14:50 UTC, gorhom commented
@magrinj thanks for submitting this CR, i was thinking about exposing a prop in the `BottomSheetModal` component that allows you to warp the bottom sheet with your own container, in your case is the `react-native-screens::FullWindowOverlay` ?

by doing this, the library still take no dependency ( other than GH and REA ) and you get to customising the container as you please .

2023-06-05 14:00 UTC, magrinj commented
@gorhom Ok, I was going this way at fist so it's automatic. But I'll change my PR, and add a prop called `bottomSheetWrapper`

2023-06-05 14:17 UTC, magrinj commented
@gorhom Done ! :)

2023-06-05 16:57 UTC, gorhom requested changes

2023-06-05 16:57 UTC, gorhom commented on CHANGELOG.md
> +## [Unreleased]
no need to modify the changelog file, it will be generated automatically with every release

2023-06-05 16:57 UTC, gorhom commented on src/components/bottomSheetModal/BottomSheetModal.tsx
> +    bottomSheetWrapper: BottomSheetWrapper = React.Fragment,
i would name it `containerComponent` , aligning with other provided components naming https://github.com/gorhom/react-native-bottom-sheet/blob/master/src/components/bottomSheet/types.d.ts#L258C6-L283

2023-06-06 10:08 UTC, magrinj commented
@gorhom I just edit regarding the requested changes

2023-06-23 19:13 UTC, merged

2023-06-23 19:14 UTC, gorhom commented
thanks @magrinj  for submitting this PR , it should be released on `v4.4.8` and `v5`

2023-08-11 21:47 UTC, peterpme commented
Hey @gorhom just a lil nudge to publish 4.4.8 if possible 😄  thank you!

2023-08-22 17:23 UTC, MarlonAEC commented
Hey @gorhom sorry for pushing but do you have any updates on release 4.4.8? I developing a scenario in which I would like to leverage this PR it will be awesome! Thanks in advance!

2023-09-03 16:40 UTC, iraybi commented
Anyone found any workaround to show BottomSheetModal on top of native Modal?

2023-09-04 09:36 UTC, thecoorum commented
I think this is something that may help here
https://github.com/intergalacticspacehighway/react-native-z-view

2023-09-14 21:45 UTC, totodot commented
I can see that new version released with new `containerComponent` props. Anyone know how to use that?
```
const Overlay = () => <FullWindowOverlay style={StyleSheet.absoluteFill} />;
```

```
<>
      <View style={styles.container}>
        <Button
          onPress={handlePresentModalPress}
          title={'Present Modal'}
          color={'black'}
        />
      </View>
      <BottomSheetModal
        containerComponent={Overlay}
        ref={bottomSheetModalRef}
        index={1}
        snapPoints={snapPoints}
        onChange={handleSheetChanges}>
        <View style={styles.contentContainer}>
          <Text>Awesome 🎉</Text>
        </View>
      </BottomSheetModal>
    </>
```

Not work as expected. I can't find bottom-sheet-modal anywhere.