fix: backdrop -> check if mounted before setting state
gorhom/react-native-bottom-sheet pull request #1657
Opened 2023-12-08 15:57 UTC by christophby

closes https://github.com/gorhom/react-native-bottom-sheet/issues/1376 (has already been closed, although it hasn't been fixed yet )

## Motivation

When using the backdrop component you could get a `"Warning: Can't perform a React state update on an unmounted component [...] in BottomSheetBackdrop"` error.

This PR adds a check if the component is mounted before setting the local state to fix that issue.

2024-01-01 15:00 UTC, gorhom commented
i tried to repo the issue but i couldn't, do you have a repo example ?

2024-01-03 11:58 UTC, christophby commented
@gorhom I don't have a repo example but I just used this component:

<details>

<summary>BottomSheet.tsx component</summary>

```typescript
import {
  BottomSheetBackdrop,
  BottomSheetBackdropProps,
  BottomSheetModal,
  BottomSheetScrollView,
} from '@gorhom/bottom-sheet';
import React, {useCallback, useRef} from 'react';
import {Button, Text, View} from 'react-native';

interface Props {}

export const BottomSheet = ({}: Props) => {
  const bottomSheetModalRef = useRef<BottomSheetModal>(null);

  const backdropComponent = useCallback(
    (props: BottomSheetBackdropProps) => (
      <BottomSheetBackdrop
        {...props}
        appearsOnIndex={0}
        disappearsOnIndex={-1}
      />
    ),
    [],
  );

  return (
    <View>
      <Button
        title="Open Bottom Sheet"
        onPress={() => {
          bottomSheetModalRef.current?.present();
        }}
      />

      <BottomSheetModal
        ref={bottomSheetModalRef}
        snapPoints={['25%']}
        backdropComponent={backdropComponent}>
        <BottomSheetScrollView>
          <>
            <Text>1 Lorem Ipsum</Text>
            <Text>2 Lorem Ipsum</Text>
          </>
        </BottomSheetScrollView>
      </BottomSheetModal>
    </View>
  );
};

```

</details>

I'm using

```
"@gorhom/bottom-sheet": "^4.5.1",
"react-native": "0.68.2",
"react-native-gesture-handler": "^2.14.0",
"react-native-reanimated": "^2.8.0",
```

https://github.com/gorhom/react-native-bottom-sheet/assets/12933672/2ef28755-f2e3-4c5f-afdb-5de23cdceaaf

2024-01-03 17:36 UTC, gorhom requested changes

2024-01-03 17:36 UTC, gorhom commented on src/components/bottomSheetBackdrop/BottomSheetBackdrop.tsx
> +  useEffect(() => {
could you move this hook to the region at the end `effects`

2024-01-03 17:36 UTC, gorhom commented
looks good, i just left a code styling comment, once it is addressed im going to merge this PR into `v4` & `v5`

2024-01-03 19:58 UTC, gorhom approved these changes

2024-01-03 19:59 UTC, merged

2024-01-04 19:00 UTC, christophby commented
Thank you for merging