Fix BottomSheetBackdrop "falsey" defaults
gorhom/react-native-bottom-sheet pull request #793
Opened 2021-12-23 01:09 UTC by jakobo

This is a change to how `BottomSheetBackdrop` handles its falsey defaults. Values such as `0` and `false` will automatically assume their fallback values instead of allowing their literal `0` or `false` to be applied. There is a reproducible Snak in #779 which shows the problem.

https://snack.expo.dev/@jakobo/bottomsheetbackdrop---appearsonindex-bug

## Motivation

The fix is to ensure that the provided value was truly undefined before assigning the default. This patch uses nullish coalesce `??` to achieve that. The following code will never render a backdrop.

```tsx
const renderBackdrop = useCallback(
  props => (
    <BottomSheetBackdrop
      {...props}
      disappearsOnIndex={-1}
      appearsOnIndex={0}
    />
  ),
  []
);
```

Under the hood, `BottomSheetBackdrop` will assign `1` for `appearsOnIndex` because JS treats `0` as false-like.

## Contributing Guidelines ✅ 
* [x] Prefer small pull requests focused on one change.
* [x] Verify that linters and tests are passing.
  * **note** There were additional unrelated prettier errors which were fixed in the second commit
* [x] Review the documentation to make sure it looks good.
* [x] Follow the pull request template when opening a pull request.
* [x] For pull requests that change the API or implementation, discuss with maintainers first by opening an issue.

2022-01-23 20:17 UTC, jakobo commented
!stale

2022-02-24 17:16 UTC, jakobo commented
!stale

2022-02-24 19:11 UTC, jakobo commented
Rebase verification (and un-stale): `Current branch jakobo/779/BottomSheetBackdrop_defaults is up to date.`

2022-03-14 00:44 UTC, IngyuTae commented
Hi, @gorhom Do you have any plan on this PR?

2022-04-13 17:53 UTC, jakobo commented
Not stale. Still relevant. Still rebased. Still passing.

2022-04-13 21:50 UTC, jakobo commented
@gorhom (ping) The fix is 3 Stalebots old. Would love to land this.

2022-04-21 08:08 UTC, gorhom requested changes

2022-04-21 08:08 UTC, gorhom commented on src/components/bottomSheetBackdrop/BottomSheetBackdrop.tsx
> +  opacity: userOpacity,
could you follow the name convection, it should be `_providedOpacity`.

https://github.com/gorhom/react-native-bottom-sheet/blob/955b7748932ba5ea81d2406c0acf7b612fecbf0e/src/components/bottomSheet/BottomSheet.tsx#L97

2022-04-21 08:09 UTC, gorhom commented
hi @jakobo, thanks for submitting this PR, i left one comment regarding the name convention for the props.

2022-04-22 19:17 UTC, jakobo commented
Applied the requested changes, @gorhom. Let me know if there's any other changes. 🎉

2022-04-22 21:02 UTC, gorhom approved these changes
thanks @jakobo for updating the naming! this will be release on the next patch release

2022-04-22 21:03 UTC, merged